<?php

declare(strict_types=1);

namespace App\Api\Sdk;

use JsonException;

/**
 * Keeps generated files inside an application-owned output directory. A prior
 * manifest grants ownership only to its named files; unrelated files survive
 * regeneration and are never removed by a recursive directory operation.
 */
final class SdkOutput
{
    private const MARKER = 'Generated by SqueHub. Do not edit directly.';

    public function __construct(private string $basePath)
    {
    }

    /** @param array<string,string> $files */
    public function sync(string $relativeOutput, array $files, string $language, bool $check): bool
    {
        $root = realpath($this->basePath);
        if ($root === false || !is_dir($root)) {
            throw new SdkException('SDK application base path is invalid.');
        }
        $segments = self::segments($relativeOutput);
        if (in_array(strtolower($segments[0]),
            ['app', 'project', 'config', 'vendor', '.git', '.env', 'public'], true)) {
            throw new SdkException('SDK output must be outside framework and application source directories.');
        }

        $directory = $root;
        foreach ($segments as $segment) {
            $directory .= DIRECTORY_SEPARATOR . $segment;
            if (is_link($directory)) {
                throw new SdkException('SDK output cannot traverse a linked directory.');
            }
            if (file_exists($directory)) {
                if (!is_dir($directory) || !self::contained($root, $directory)) {
                    throw new SdkException('SDK output directory is unsafe.');
                }
            } elseif (!$check && !@mkdir($directory, 0775)) {
                throw new SdkException('SDK output directory could not be created.');
            }
        }
        if (!is_dir($directory)) return false;

        foreach ($files as $name => $contents) {
            self::fileName($name);
            if ($name !== 'squehub-sdk.json' && !self::isGenerated($name, $contents)) {
                throw new SdkException('SDK emitter produced a file without its generated marker.');
            }
        }

        $manifestPath = $directory . DIRECTORY_SEPARATOR . 'squehub-sdk.json';
        $owned = $this->ownedFiles($manifestPath, $language);
        foreach ($files as $name => $_) {
            $path = self::filePath($directory, $name);
            self::prepareParent($directory, $name, false);
            if (is_link($path) || (file_exists($path) && !is_file($path))) {
                throw new SdkException('SDK output contains an unsafe target.');
            }
            if (is_file($path) && $name !== 'squehub-sdk.json' && !isset($owned[$name])) {
                throw new SdkException('SDK output would overwrite a file it does not own.');
            }
        }
        foreach ($owned as $name => $_) {
            $path = self::filePath($directory, $name);
            self::prepareParent($directory, $name, false);
            if (is_link($path) || (file_exists($path) && !is_file($path))) {
                throw new SdkException('SDK manifest references an unsafe file.');
            }
            if (is_file($path) && !self::isGenerated($name, (string) file_get_contents($path))) {
                throw new SdkException('SDK owned file no longer has its generated marker.');
            }
        }

        if ($check) {
            foreach ($files as $name => $contents) {
                $path = self::filePath($directory, $name);
                if (!is_file($path) || file_get_contents($path) !== $contents) return false;
            }
            foreach ($owned as $name => $_) {
                if (!array_key_exists($name, $files)) return false;
            }
            return true;
        }

        foreach ($files as $name => $contents) {
            if ($name === 'squehub-sdk.json') continue;
            $path = self::filePath($directory, $name);
            self::prepareParent($directory, $name, true);
            self::write($path, $contents);
        }
        foreach ($owned as $name => $_) {
            if (array_key_exists($name, $files)) continue;
            $path = self::filePath($directory, $name);
            if (is_file($path) && !@unlink($path)) {
                throw new SdkException('SDK stale generated file could not be removed.');
            }
        }
        self::write($manifestPath, $files['squehub-sdk.json']);
        return true;
    }

    /** @return array<string,true> */
    private function ownedFiles(string $path, string $language): array
    {
        if (!file_exists($path)) return [];
        if (!is_file($path) || is_link($path) || filesize($path) > 262144) {
            throw new SdkException('SDK generation manifest is invalid.');
        }
        try {
            $manifest = json_decode((string) file_get_contents($path), true, 32, JSON_THROW_ON_ERROR);
        } catch (JsonException $exception) {
            throw new SdkException('SDK generation manifest is invalid.', 0, $exception);
        }
        if (!is_array($manifest) || ($manifest['squehub_sdk'] ?? null) !== '1'
            || ($manifest['language'] ?? null) !== $language
            || !isset($manifest['files']) || !is_array($manifest['files'])
            || !array_is_list($manifest['files'])) {
            throw new SdkException('SDK generation manifest is invalid or belongs to another language.');
        }
        $owned = [];
        foreach ($manifest['files'] as $name) {
            if (!is_string($name)) {
                throw new SdkException('SDK generation manifest file list is invalid.');
            }
            self::fileName($name);
            if ($name === 'squehub-sdk.json' || isset($owned[$name])) {
                throw new SdkException('SDK generation manifest file list is invalid.');
            }
            $owned[$name] = true;
        }
        return $owned;
    }

    /** @return list<string> */
    private static function segments(string $path): array
    {
        if ($path === '' || preg_match('~\A(?:[A-Za-z]:|[/\\\\])~', $path) === 1) {
            throw new SdkException('SDK output must be a nonempty relative path.');
        }
        $parts = explode('/', str_replace('\\', '/', $path));
        foreach ($parts as $part) {
            if ($part === '' || $part === '.' || $part === '..'
                || preg_match('/[<>:"|?*\x00-\x1F\x7F]/', $part) === 1
                || str_ends_with($part, '.') || str_ends_with($part, ' ')) {
                throw new SdkException('SDK output path contains an unsafe component.');
            }
        }
        return $parts;
    }

    private static function fileName(string $name): void
    {
        if ($name === '' || str_contains($name, '\\')
            || preg_match('~\A[A-Za-z0-9_.-]+(?:/[A-Za-z0-9_.-]+)*\z~D', $name) !== 1) {
            throw new SdkException('SDK emitter file name is unsafe.');
        }
        foreach (explode('/', $name) as $part) {
            if ($part === '.' || $part === '..') {
                throw new SdkException('SDK emitter file name is unsafe.');
            }
        }
    }

    private static function filePath(string $directory, string $name): string
    {
        self::fileName($name);
        return $directory . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $name);
    }

    /** Check each component before creating it, so a user-owned link cannot redirect writes. */
    private static function prepareParent(string $directory, string $name, bool $create): void
    {
        $parts = explode('/', $name);
        array_pop($parts);
        $parent = $directory;
        foreach ($parts as $part) {
            $parent .= DIRECTORY_SEPARATOR . $part;
            if (is_link($parent)) {
                throw new SdkException('SDK source directory is unsafe.');
            }
            if (file_exists($parent)) {
                if (!is_dir($parent) || !self::contained($directory, $parent)) {
                    throw new SdkException('SDK source directory is unsafe.');
                }
            } elseif ($create && !@mkdir($parent, 0775)) {
                throw new SdkException('SDK source directory could not be created.');
            }
        }
    }

    private static function isGenerated(string $name, string $contents): bool
    {
        if ($name === 'package.json' || $name === 'composer.json') return true;
        return str_contains(substr($contents, 0, 256), self::MARKER);
    }

    private static function contained(string $root, string $path): bool
    {
        $resolved = realpath($path);
        if ($resolved === false) return false;
        if (PHP_OS_FAMILY === 'Windows' ? strcasecmp($resolved, $root) === 0
            : strcmp($resolved, $root) === 0) return true;
        $prefix = rtrim($root, '/\\') . DIRECTORY_SEPARATOR;
        return PHP_OS_FAMILY === 'Windows'
            ? strncasecmp($resolved, $prefix, strlen($prefix)) === 0
            : strncmp($resolved, $prefix, strlen($prefix)) === 0;
    }

    private static function write(string $path, string $contents): void
    {
        $temporary = @tempnam(dirname($path), '.squehub-');
        if ($temporary === false) {
            throw new SdkException('SDK output file could not be prepared.');
        }
        try {
            if (file_put_contents($temporary, $contents) !== strlen($contents)
                || !@rename($temporary, $path)) {
                throw new SdkException('SDK output file could not be written.');
            }
        } finally {
            if (is_file($temporary)) @unlink($temporary);
        }
    }
}
