<?php

declare(strict_types=1);

namespace App\Api\Sdk\Emitters;

use App\Api\Sdk\SdkModel;
use JsonException;
use LogicException;

/** Shared structured rendering for the two independent ES module targets. */
abstract class EcmaScriptEmitter
{
    private const MARKER = '// Generated by SqueHub. Do not edit directly.';

    /** @return array<string, string> */
    final protected function render(SdkModel $model, bool $typescript): array
    {
        $extension = $typescript ? 'ts' : 'js';
        $files = [
            'client.' . $extension => $this->client($model, $typescript),
            'types.' . $extension => $typescript ? $this->typeScriptTypes($model) : $this->javaScriptTypes($model),
            'errors.' . $extension => $typescript ? $this->typeScriptErrors() : $this->javaScriptErrors(),
            'runtime.' . $extension => $typescript ? $this->typeScriptRuntime() : $this->javaScriptRuntime(),
            'index.' . $extension => $this->index($model, $typescript),
        ];
        if (!$typescript) {
            $files['package.json'] = "{\n  \"type\": \"module\"\n}\n";
        }
        ksort($files, SORT_STRING);
        return $files;
    }

    private function client(SdkModel $model, bool $typescript): string
    {
        $lines = [self::MARKER];
        if ($typescript) {
            $lines[] = 'import { createRequester, type ClientOptions, type OperationSpec, type Requester } from "./runtime.js";';
            $imports = [];
            foreach ($model->operations as $operation) {
                $imports[] = $operation['symbol'] . 'Response';
                if ($this->hasArguments($operation)) $imports[] = $operation['symbol'] . 'Args';
            }
            if ($imports !== []) {
                sort($imports, SORT_STRING);
                $lines[] = 'import type { ' . implode(', ', $imports) . ' } from "./types.js";';
            }
        } else {
            $lines[] = 'import { createRequester } from "./runtime.js";';
        }
        $lines[] = '';

        foreach ($model->operations as $operation) {
            $name = $operation['symbol'];
            $spec = $this->operationSpec($operation);
            $declaration = 'const spec' . $name . ($typescript ? ': OperationSpec' : '')
                . ' = ' . self::json($spec) . ';';
            $lines[] = $declaration;
        }
        if ($model->operations !== []) $lines[] = '';

        if ($typescript) {
            $lines[] = 'export class SqueHubClient {';
            $lines[] = '  private readonly _requester: Requester;';
            $lines[] = '';
            $lines[] = '  constructor(options: ClientOptions) {';
            $lines[] = '    this._requester = createRequester(options);';
            $lines[] = '  }';
        } else {
            $lines[] = 'export class SqueHubClient {';
            $lines[] = '  /** @param {import("./runtime.js").ClientOptions} options */';
            $lines[] = '  constructor(options) {';
            $lines[] = '    this._requester = createRequester(options);';
        }

        $tree = $this->operationTree($model->operations);
        if ($typescript) {
            foreach ($tree as $segment => $node) {
                $lines[] = '';
                $lines[] = '  readonly ' . $segment . ' = ' . $this->renderNode($node, 2, true) . ';';
            }
            $lines[] = '}';
        } else {
            foreach ($tree as $segment => $node) {
                if (isset($node['operation'])) {
                    $lines[] = '    ' . $this->jsMethodAnnotation($node['operation']);
                }
                $lines[] = '    this.' . $segment . ' = ' . $this->renderNode($node, 2, false) . ';';
            }
            $lines[] = '  }';
            $lines[] = '}';
        }
        return implode("\n", $lines) . "\n";
    }

    /** @param list<array<string,mixed>> $operations @return array<string,mixed> */
    private function operationTree(array $operations): array
    {
        $tree = [];
        foreach ($operations as $operation) {
            $node =& $tree;
            foreach ($operation['segments'] as $segment) {
                if (!is_string($segment) || preg_match('/\A[A-Za-z_$][A-Za-z0-9_$]*\z/D', $segment) !== 1) {
                    throw new LogicException('SDK operation has an invalid JavaScript symbol.');
                }
                $node =& $node[$segment];
            }
            if ($node !== null) {
                throw new LogicException('SDK operation symbols collide.');
            }
            $node = ['operation' => $operation];
            unset($node);
        }
        ksort($tree, SORT_STRING);
        return $tree;
    }

    /** @param array<string,mixed> $node */
    private function renderNode(array $node, int $depth, bool $typescript): string
    {
        if (isset($node['operation'])) {
            $operation = $node['operation'];
            $name = $operation['symbol'];
            $hasArgs = $this->hasArguments($operation);
            $required = $this->hasRequiredArguments($operation);
            $argument = !$hasArgs ? '' : ($typescript ? 'args: ' . $name . 'Args' : 'args')
                . ($required ? '' : ' = {}');
            $result = $typescript ? ': Promise<' . $name . 'Response>' : '';
            $call = 'this._requester(spec' . $name . ', ' . ($hasArgs ? 'args' : '{}') . ')';
            if ($typescript) $call .= ' as Promise<' . $name . 'Response>';
            return '(' . $argument . ')' . $result . ' => ' . $call;
        }
        $indent = str_repeat('  ', $depth);
        $inside = str_repeat('  ', $depth + 1);
        $lines = ['Object.freeze({'];
        ksort($node, SORT_STRING);
        foreach ($node as $segment => $child) {
            if (!$typescript && isset($child['operation'])) {
                $lines[] = $inside . $this->jsMethodAnnotation($child['operation']);
            }
            $lines[] = $inside . $segment . ': ' . $this->renderNode($child, $depth + 1, $typescript) . ',';
        }
        $lines[] = $indent . '})';
        return implode("\n", $lines);
    }

    /** @param array<string,mixed> $operation */
    private function jsMethodAnnotation(array $operation): string
    {
        $name = $operation['symbol'];
        $argument = $this->hasArguments($operation)
            ? '(args' . ($this->hasRequiredArguments($operation) ? '' : '?')
                . ': import("./types.js").' . $name . 'Args)'
            : '()';
        return '/** @type {' . $argument . ' => Promise<import("./types.js").'
            . $name . 'Response>} */';
    }

    /** @param array<string,mixed> $operation @return array<string,mixed> */
    private function operationSpec(array $operation): array
    {
        $path = [];
        $query = [];
        $headers = [];
        foreach ($operation['parameters'] as $parameter) {
            $entry = ['name' => $parameter['name'], 'required' => $parameter['required']];
            if (is_array($parameter['schema']) && array_key_exists('const', $parameter['schema'])) {
                $entry['fixed'] = $parameter['schema']['const'];
            }
            switch ($parameter['in']) {
                case 'path': $path[] = $entry; break;
                case 'query': $query[] = $entry; break;
                case 'header': $headers[] = $entry; break;
                default: throw new LogicException('SDK parameter location is unsupported.');
            }
        }
        $success = [];
        foreach ($operation['responses'] as $status => $response) {
            if ((int) $status < 200 || (int) $status > 299) continue;
            $success[] = ['status' => (int) $status, 'body' => $response['schema'] !== null,
                'contentType' => $response['content_type']];
        }
        if ($success === []) {
            throw new LogicException('SDK operation has no declared success response.');
        }
        usort($success, static fn (array $a, array $b): int => $a['status'] <=> $b['status']);
        $accepted = [];
        foreach ($success as $response) {
            if ($response['contentType'] === null) continue;
            $mediaType = strtolower(trim(explode(';', $response['contentType'], 2)[0]));
            $accepted[$mediaType] = true;
        }
        unset($accepted['application/json']);
        ksort($accepted, SORT_STRING);
        $accept = implode(', ', [...array_keys($accepted), 'application/json']);
        return [
            'method' => $operation['method'],
            'path' => $operation['path'],
            'security' => $operation['security']['type'],
            'pathParams' => $path,
            'query' => $query,
            'headers' => $headers,
            'body' => $operation['request_body'] !== null,
            'bodyRequired' => $operation['request_body']['required'] ?? false,
            'requestContentType' => $operation['request_body']['content_type'] ?? null,
            'accept' => $accept,
            'success' => $success,
        ];
    }

    /** @param array<string,mixed> $operation */
    private function hasArguments(array $operation): bool
    {
        foreach ($operation['parameters'] as $parameter) {
            if (!is_array($parameter['schema']) || !array_key_exists('const', $parameter['schema'])) return true;
        }
        return $operation['request_body'] !== null;
    }

    /** @param array<string,mixed> $operation */
    private function hasRequiredArguments(array $operation): bool
    {
        foreach ($operation['parameters'] as $parameter) {
            if ($parameter['required'] && (!is_array($parameter['schema'])
                || !array_key_exists('const', $parameter['schema']))) return true;
        }
        return ($operation['request_body']['required'] ?? false) === true;
    }

    private function typeScriptTypes(SdkModel $model): string
    {
        $lines = [self::MARKER, ''];
        if (isset($model->schemaSymbols['SqueHubPaginationMeta'])) {
            $lines[] = 'export type SqueHubPage<T> = { data: T[]; meta: SqueHubPaginationMeta };';
            $lines[] = '';
        }
        foreach ($model->schemas as $name => $schema) {
            $symbol = $model->schemaSymbols[$name];
            $lines[] = 'export type ' . $symbol . ' = ' . $this->type($schema, $model, false) . ';';
            $lines[] = 'export type ' . $symbol . 'Input = ' . $this->type($schema, $model, true) . ';';
            $lines[] = '';
        }
        foreach ($model->operations as $operation) {
            $name = $operation['symbol'];
            if ($this->hasArguments($operation)) {
                $lines[] = 'export type ' . $name . 'Args = ' . $this->argsType($operation, $model) . ';';
            }
            $lines[] = 'export type ' . $name . 'Response = ' . $this->responseType($operation, $model) . ';';
            $lines[] = '';
        }
        return rtrim(implode("\n", $lines)) . "\n";
    }

    private function javaScriptTypes(SdkModel $model): string
    {
        $lines = [self::MARKER, ''];
        if (isset($model->schemaSymbols['SqueHubPaginationMeta'])) {
            $lines[] = '/** @template T @typedef {{data: T[], meta: SqueHubPaginationMeta}} SqueHubPage */';
            $lines[] = '';
        }
        foreach ($model->schemas as $name => $schema) {
            $symbol = $model->schemaSymbols[$name];
            foreach ([false, true] as $input) {
                $target = $symbol . ($input ? 'Input' : '');
                $lines[] = '/** @typedef {' . $this->jsdocType($schema, $model, $input) . '} ' . $target . ' */';
            }
            $lines[] = '';
        }
        foreach ($model->operations as $operation) {
            $name = $operation['symbol'];
            if ($this->hasArguments($operation)) {
                $lines[] = '/** @typedef {' . $this->argsType($operation, $model, true) . '} ' . $name . 'Args */';
            }
            $lines[] = '/** @typedef {' . $this->responseType($operation, $model, true) . '} '
                . $name . 'Response */';
            $lines[] = '';
        }
        $lines[] = 'export {};';
        return implode("\n", $lines) . "\n";
    }

    /** @param array<string,mixed> $operation */
    private function argsType(array $operation, SdkModel $model, bool $jsdoc = false): string
    {
        $groups = ['path' => [], 'query' => [], 'header' => []];
        $groupRequired = ['path' => false, 'query' => false, 'header' => false];
        foreach ($operation['parameters'] as $parameter) {
            if (is_array($parameter['schema']) && array_key_exists('const', $parameter['schema'])) continue;
            $location = $parameter['in'];
            $groups[$location][] = self::json($parameter['name']) . ($parameter['required'] ? '' : '?')
                . ': ' . ($jsdoc ? $this->jsdocType($parameter['schema'], $model, true)
                    : $this->type($parameter['schema'], $model, true));
            if ($parameter['required']) $groupRequired[$location] = true;
        }
        $fields = [];
        foreach (['path', 'query', 'header'] as $location) {
            if ($groups[$location] === []) continue;
            $property = $location === 'header' ? 'headers' : $location;
            $fields[] = $property . ($groupRequired[$location] ? '' : '?')
                . ': { ' . implode('; ', $groups[$location]) . ' }';
        }
        if ($operation['request_body'] !== null) {
            $fields[] = 'body' . ($operation['request_body']['required'] ? '' : '?') . ': '
                . ($jsdoc ? $this->jsdocType($operation['request_body']['schema'], $model, true)
                    : $this->type($operation['request_body']['schema'], $model, true));
        }
        return '{ ' . implode('; ', $fields) . ' }';
    }

    /** @param array<string,mixed> $operation */
    private function responseType(array $operation, SdkModel $model, bool $jsdoc = false): string
    {
        $types = [];
        foreach ($operation['responses'] as $status => $response) {
            if ((int) $status < 200 || (int) $status > 299) continue;
            $types[] = $response['schema'] === null ? ($jsdoc ? 'undefined' : 'void')
                : ($jsdoc ? $this->jsdocType($response['schema'], $model, false)
                    : $this->type($response['schema'], $model, false));
        }
        $types = array_values(array_unique($types));
        sort($types, SORT_STRING);
        return implode(' | ', $types);
    }

    /** @param array<string,mixed>|bool $schema */
    private function type(array|bool $schema, SdkModel $model, bool $input): string
    {
        if ($schema === true) return 'unknown';
        if ($schema === false) return 'never';
        if (isset($schema['$ref'])) {
            $name = substr($schema['$ref'], strlen('#/components/schemas/'));
            return $model->schemaSymbols[$name] . ($input ? 'Input' : '');
        }
        if (array_key_exists('const', $schema)) return self::json($schema['const']);
        if (isset($schema['enum'])) {
            $values = array_map(self::json(...), $schema['enum']);
            sort($values, SORT_STRING);
            return implode(' | ', $values);
        }
        foreach (['oneOf', 'anyOf', 'allOf'] as $composition) {
            if (!isset($schema[$composition])) continue;
            $parts = array_map(fn (array|bool $part): string => '(' . $this->type($part, $model, $input) . ')',
                $schema[$composition]);
            return implode($composition === 'allOf' ? ' & ' : ' | ', $parts);
        }
        $types = (array) ($schema['type'] ?? []);
        if ($types === []) return 'unknown';
        $parts = [];
        foreach ($types as $type) {
            $parts[] = match ($type) {
                'null' => 'null',
                'string' => 'string',
                'integer', 'number' => 'number',
                'boolean' => 'boolean',
                'array' => '(' . $this->type($schema['items'] ?? true, $model, $input) . ')[]',
                'object' => $this->pageItem($schema, $model, $input) !== null
                    ? 'SqueHubPage<' . $this->type($this->pageItem($schema, $model, $input), $model, false) . '>'
                    : $this->objectType($schema, $model, $input),
                default => throw new LogicException('SDK schema type is unsupported.'),
            };
        }
        $parts = array_values(array_unique($parts));
        return implode(' | ', $parts);
    }

    /** @param array<string,mixed> $schema @return array<string,mixed>|bool|null */
    private function pageItem(array $schema, SdkModel $model, bool $input): array|bool|null
    {
        if ($input || !isset($model->schemaSymbols['SqueHubPaginationMeta'])
            || ($schema['type'] ?? null) !== 'object'
            || array_keys($schema['properties'] ?? []) !== ['data', 'meta']
            || !isset($schema['properties']['data']['items'])
            || ($schema['properties']['data']['type'] ?? null) !== 'array'
            || ($schema['properties']['meta']['$ref'] ?? null)
                !== '#/components/schemas/SqueHubPaginationMeta') {
            return null;
        }
        $required = $schema['required'] ?? [];
        sort($required, SORT_STRING);
        return $required === ['data', 'meta'] ? $schema['properties']['data']['items'] : null;
    }

    /** @param array<string,mixed> $schema */
    private function objectType(array $schema, SdkModel $model, bool $input): string
    {
        $fields = [];
        $properties = $schema['properties'] ?? [];
        $required = $schema['required'] ?? [];
        foreach ($properties as $name => $property) {
            if ($input && ($property['readOnly'] ?? false)) continue;
            if (!$input && ($property['writeOnly'] ?? false)) continue;
            $fields[] = self::json($name) . (in_array($name, $required, true) ? '' : '?')
                . ': ' . $this->type($property, $model, $input);
        }
        $additional = $schema['additionalProperties'] ?? true;
        if ($additional !== false) {
            $extraType = $additional === true ? 'unknown' : $this->type($additional, $model, $input);
            if ($fields === []) return 'Record<string, ' . $extraType . '>';
            // Declared properties are JSON Schema exceptions to the additional
            // value constraint; a broad index preserves those legal objects.
            $fields[] = '[key: string]: unknown';
        }
        if ($fields === []) return 'Record<string, never>';
        return '{ ' . implode('; ', $fields) . ' }';
    }

    /** @param array<string,mixed>|bool $schema */
    private function jsdocType(array|bool $schema, SdkModel $model, bool $input): string
    {
        // TypeScript understands these type expressions in JSDoc. Rewriting
        // tokens as raw text would also rewrite quoted enum values and keys.
        // A literal comment terminator in a schema string must not escape the
        // JSDoc block and become executable JavaScript source.
        return str_replace('*/', '*\\u002F', $this->type($schema, $model, $input));
    }

    private function index(SdkModel $model, bool $typescript): string
    {
        $lines = [self::MARKER, 'export { SqueHubClient } from "./client.js";',
            'export { SqueHubApiError, SqueHubProtocolError, SqueHubTransportError } from "./errors.js";'];
        if ($typescript) {
            $lines[] = 'export type { ClientOptions, TokenProvider } from "./runtime.js";';
            $types = [];
            if (isset($model->schemaSymbols['SqueHubPaginationMeta'])) $types[] = 'SqueHubPage';
            foreach ($model->schemaSymbols as $name => $symbol) {
                $types[] = $symbol;
                $types[] = $symbol . 'Input';
            }
            foreach ($model->operations as $operation) {
                $types[] = $operation['symbol'] . 'Response';
                if ($this->hasArguments($operation)) $types[] = $operation['symbol'] . 'Args';
            }
            if ($types !== []) {
                sort($types, SORT_STRING);
                $lines[] = 'export type { ' . implode(', ', $types) . ' } from "./types.js";';
            }
        }
        return implode("\n", $lines) . "\n";
    }

    private static function json(mixed $value): string
    {
        try {
            return json_encode($value, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES
                | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
        } catch (JsonException $exception) {
            throw new LogicException('SDK source value could not be encoded.', 0, $exception);
        }
    }

    private function typeScriptErrors(): string
    {
        return self::MARKER . "\n" . <<<'TS'
export type SafeResponseHeaders = Readonly<Record<string, string>>;

export class SqueHubApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly details: unknown;
  readonly requestId: string | null;
  readonly headers: SafeResponseHeaders;

  constructor(status: number, code: string, message: string, details: unknown,
    requestId: string | null, headers: SafeResponseHeaders) {
    super(message);
    this.name = "SqueHubApiError";
    this.status = status;
    this.code = code;
    this.details = details;
    this.requestId = requestId;
    this.headers = headers;
  }
}

export class SqueHubProtocolError extends Error {
  readonly status: number | null;

  constructor(message: string, status: number | null = null) {
    super(message);
    this.name = "SqueHubProtocolError";
    this.status = status;
  }
}

export class SqueHubTransportError extends Error {
  constructor() {
    super("The API request could not be completed.");
    this.name = "SqueHubTransportError";
  }
}
TS
            . "\n";
    }

    private function javaScriptErrors(): string
    {
        return self::MARKER . "\n" . <<<'JS'
export class SqueHubApiError extends Error {
  /** @param {number} status @param {string} code @param {string} message
   * @param {unknown} details @param {string|null} requestId
   * @param {Readonly<Record<string,string>>} headers */
  constructor(status, code, message, details, requestId, headers) {
    super(message);
    this.name = "SqueHubApiError";
    this.status = status;
    this.code = code;
    this.details = details;
    this.requestId = requestId;
    this.headers = headers;
  }
}

export class SqueHubProtocolError extends Error {
  /** @param {string} message @param {number|null} [status] */
  constructor(message, status = null) {
    super(message);
    this.name = "SqueHubProtocolError";
    this.status = status;
  }
}

export class SqueHubTransportError extends Error {
  constructor() {
    super("The API request could not be completed.");
    this.name = "SqueHubTransportError";
  }
}
JS
            . "\n";
    }

    private function typeScriptRuntime(): string
    {
        return self::MARKER . "\n" . <<<'TS'
import { SqueHubApiError, SqueHubProtocolError, SqueHubTransportError } from "./errors.js";

export type TokenProvider = string | (() => string | null | undefined | Promise<string | null | undefined>);
export type ClientOptions = {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  token?: TokenProvider;
  credentials?: RequestCredentials;
  csrfToken?: TokenProvider;
  csrfHeader?: string;
};
type Scalar = string | number | boolean;
type ParameterSpec = { name: string; required: boolean; fixed?: Scalar };
type SuccessSpec = { status: number; body: boolean; contentType: string | null };
export type OperationSpec = {
  method: string;
  path: string;
  security: "none" | "pat" | "session";
  pathParams: readonly ParameterSpec[];
  query: readonly ParameterSpec[];
  headers: readonly ParameterSpec[];
  body: boolean;
  bodyRequired: boolean;
  requestContentType: string | null;
  accept: string;
  success: readonly SuccessSpec[];
};
export type RequestArgs = {
  path?: Record<string, Scalar | undefined>;
  query?: Record<string, Scalar | undefined>;
  headers?: Record<string, Scalar | undefined>;
  body?: unknown;
};
export type Requester = (spec: OperationSpec, args?: RequestArgs) => Promise<unknown>;

const SAFE_RESPONSE_HEADERS = ["retry-after", "x-ratelimit-limit", "x-ratelimit-remaining",
  "x-ratelimit-reset", "x-request-id", "allow"] as const;
const HEADER_NAME = /^[!#$%&'*+.^_`|~0-9A-Za-z-]+$/;

function scalar(value: unknown): string {
  if (typeof value !== "string" && typeof value !== "number" && typeof value !== "boolean") {
    throw new SqueHubProtocolError("An API parameter must be a scalar value.");
  }
  if (typeof value === "number" && !Number.isFinite(value)) {
    throw new SqueHubProtocolError("An API number must be finite.");
  }
  return String(value);
}

function ownValue(group: Record<string, Scalar | undefined> | undefined, name: string): Scalar | undefined {
  return group && Object.prototype.hasOwnProperty.call(group, name) ? group[name] : undefined;
}

function headerValue(value: unknown): string {
  const result = scalar(value);
  if (/[\r\n\0]/.test(result)) throw new SqueHubProtocolError("An API header value is invalid.");
  return result;
}

function pathSegment(value: unknown): string {
  const segment = scalar(value);
  if (segment === "" || segment === "." || segment === ".."
    || /[\/\\\x00-\x1F\x7F]/.test(segment)) {
    throw new SqueHubProtocolError("A path parameter is not a valid route segment.");
  }
  try { return encodeURIComponent(segment); }
  catch { throw new SqueHubProtocolError("A path parameter cannot be encoded."); }
}

function jsonValue(value: unknown, seen: WeakSet<object>, depth = 0): void {
  if (depth > 64) throw new SqueHubProtocolError("The JSON request body is too deeply nested.");
  if (value === null || typeof value === "string" || typeof value === "boolean") return;
  if (typeof value === "number" && Number.isFinite(value)) return;
  if (Array.isArray(value)) {
    if (seen.has(value)) throw new SqueHubProtocolError("The JSON request body is cyclic.");
    seen.add(value);
    for (const item of value) jsonValue(item, seen, depth + 1);
    seen.delete(value);
    return;
  }
  if (typeof value === "object" && value !== null
    && (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null)) {
    if (seen.has(value)) throw new SqueHubProtocolError("The JSON request body is cyclic.");
    seen.add(value);
    // JSON.stringify omits absent object properties represented as undefined.
    // Arrays keep their stricter rule because undefined becomes a null slot.
    for (const item of Object.values(value)) {
      if (item !== undefined) jsonValue(item, seen, depth + 1);
    }
    seen.delete(value);
    return;
  }
  throw new SqueHubProtocolError("The request body must contain JSON values only.");
}

async function resolveToken(provider: TokenProvider | undefined): Promise<string | null> {
  let value: string | null | undefined;
  try { value = typeof provider === "function" ? await provider() : provider; }
  catch { throw new SqueHubProtocolError("A runtime credential could not be resolved."); }
  if (value === null || value === undefined) return null;
  if (typeof value !== "string" || value === "" || /[\r\n\0]/.test(value)) {
    throw new SqueHubProtocolError("A runtime credential is invalid.");
  }
  return value;
}

function safeHeaders(headers: Headers): Readonly<Record<string, string>> {
  const result: Record<string, string> = {};
  for (const name of SAFE_RESPONSE_HEADERS) {
    const value = headers.get(name);
    if (value !== null) result[name] = value.slice(0, 256);
  }
  return Object.freeze(result);
}

function jsonMediaType(contentType: string | null): boolean {
  if (contentType === null) return false;
  const type = contentType.split(";", 1)[0].trim().toLowerCase();
  return type === "application/json"
    || /^application\/[a-z0-9!#$&^_.+-]+\+json$/.test(type);
}

function declaredJsonMediaType(contentType: string | null, declared: string | null): boolean {
  return jsonMediaType(contentType) && contentType!.split(";", 1)[0].trim().toLowerCase()
    === declared?.toLowerCase();
}

function validateArguments(spec: OperationSpec, args: RequestArgs): void {
  if (args === null || typeof args !== "object" || Array.isArray(args)) {
    throw new SqueHubProtocolError("API arguments must be an object.");
  }
  for (const name of Object.keys(args)) {
    if (!["path", "query", "headers", "body"].includes(name)) {
      throw new SqueHubProtocolError("An API argument group is unknown.");
    }
  }
  const groups: readonly ["path" | "query" | "headers", readonly ParameterSpec[]][] = [
    ["path", spec.pathParams], ["query", spec.query], ["headers", spec.headers],
  ];
  for (const [name, parameters] of groups) {
    const values = args[name];
    if (values === undefined) continue;
    if (values === null || typeof values !== "object" || Array.isArray(values)
      || ![Object.prototype, null].includes(Object.getPrototypeOf(values))) {
      throw new SqueHubProtocolError("API parameters must be keyed objects.");
    }
    for (const key of Object.keys(values)) {
      const parameter = parameters.find(item => item.name === key);
      if (!parameter) throw new SqueHubProtocolError("An API parameter is undeclared.");
      if (parameter.fixed !== undefined && values[key] !== parameter.fixed) {
        throw new SqueHubProtocolError("An API parameter conflicts with the contract.");
      }
    }
  }
  if (!spec.body && Object.prototype.hasOwnProperty.call(args, "body")) {
    throw new SqueHubProtocolError("This API operation has no request body.");
  }
}

export function createRequester(options: ClientOptions): Requester {
  if (!options || typeof options.baseUrl !== "string") {
    throw new SqueHubProtocolError("A base URL is required.");
  }
  let base: URL;
  try { base = new URL(options.baseUrl); }
  catch { throw new SqueHubProtocolError("The base URL is invalid."); }
  if (!/^https?:$/.test(base.protocol) || base.username || base.password
    || /[?#]/.test(options.baseUrl) || base.search || base.hash) {
    throw new SqueHubProtocolError("The base URL must be an HTTP URL without credentials, query, or fragment.");
  }
  const fetcher = options.fetch ?? globalThis.fetch?.bind(globalThis);
  if (typeof fetcher !== "function") throw new SqueHubProtocolError("A Fetch implementation is required.");
  const baseUrl = base.href.replace(/\/+$/, "");
  const csrfHeader = options.csrfHeader ?? "X-CSRF-Token";
  if (!HEADER_NAME.test(csrfHeader) || /^(authorization|cookie|content-length|host)$/i.test(csrfHeader)) {
    throw new SqueHubProtocolError("The CSRF header name is invalid.");
  }

  return async (spec: OperationSpec, args: RequestArgs = {}): Promise<unknown> => {
    validateArguments(spec, args);
    let path = spec.path;
    for (const parameter of spec.pathParams) {
      const value = parameter.fixed ?? ownValue(args.path, parameter.name);
      if (value === undefined || value === null) {
        throw new SqueHubProtocolError("A required path parameter is missing.");
      }
      path = path.replace("{" + parameter.name + "}", pathSegment(value));
    }
    const url = new URL(baseUrl + (path.startsWith("/") ? path : "/" + path));
    for (const parameter of spec.query) {
      const value = parameter.fixed ?? ownValue(args.query, parameter.name);
      if (value === undefined) {
        if (parameter.required) throw new SqueHubProtocolError("A required query parameter is missing.");
        continue;
      }
      if (value === null) throw new SqueHubProtocolError("A query parameter cannot be null.");
      url.searchParams.append(parameter.name, scalar(value));
    }
    const headers = new Headers({ Accept: spec.accept });
    for (const parameter of spec.headers) {
      const value = parameter.fixed ?? ownValue(args.headers, parameter.name);
      if (value === undefined) {
        if (parameter.required) throw new SqueHubProtocolError("A required header parameter is missing.");
        continue;
      }
      headers.set(parameter.name, headerValue(value));
    }
    if (spec.security === "pat") {
      const token = await resolveToken(options.token);
      if (token !== null) headers.set("Authorization", "Bearer " + token);
    }
    if (spec.security === "session" && !/^(GET|HEAD|OPTIONS)$/i.test(spec.method)) {
      const csrf = await resolveToken(options.csrfToken);
      if (csrf !== null) headers.set(csrfHeader, csrf);
    }
    let body: string | undefined;
    if (spec.body) {
      if (!Object.prototype.hasOwnProperty.call(args, "body")) {
        if (spec.bodyRequired) throw new SqueHubProtocolError("A required JSON request body is missing.");
      } else {
        try {
          jsonValue(args.body, new WeakSet<object>());
          body = JSON.stringify(args.body);
        } catch (error) {
          if (error instanceof SqueHubProtocolError) throw error;
          throw new SqueHubProtocolError("The JSON request body could not be serialized.");
        }
        if (body === undefined) throw new SqueHubProtocolError("The JSON request body is invalid.");
        headers.set("Content-Type", spec.requestContentType ?? "application/json");
      }
    }
    let response: Response;
    try {
      response = await fetcher(url.toString(), {
        method: spec.method, headers, body,
        credentials: spec.security === "session" ? (options.credentials ?? "same-origin") : "omit",
      });
    } catch {
      throw new SqueHubTransportError();
    }
    const declared = spec.success.find(item => item.status === response.status);
    if (declared) {
      if (!declared.body) return undefined;
      if (!declaredJsonMediaType(response.headers.get("content-type"), declared.contentType)) {
        throw new SqueHubProtocolError("The API success response is not JSON.", response.status);
      }
      try { return await response.json(); }
      catch { throw new SqueHubProtocolError("The API success response contains invalid JSON.", response.status); }
    }
    if (response.status >= 200 && response.status < 300) {
      throw new SqueHubProtocolError("The API returned an undeclared success status.", response.status);
    }
    if (!jsonMediaType(response.headers.get("content-type"))) {
      throw new SqueHubProtocolError("The API error response is not JSON.", response.status);
    }
    let payload: unknown;
    try { payload = await response.json(); }
    catch { throw new SqueHubProtocolError("The API error response contains invalid JSON.", response.status); }
    if (!payload || typeof payload !== "object" || !("error" in payload)
      || !payload.error || typeof payload.error !== "object"
      || !("code" in payload.error) || typeof payload.error.code !== "string"
      || !("message" in payload.error) || typeof payload.error.message !== "string"
      || !("request_id" in payload) || typeof payload.request_id !== "string") {
      throw new SqueHubProtocolError("The API returned an unknown error response.", response.status);
    }
    const error = payload.error as { code: string; message: string; details?: unknown };
    const requestId = payload.request_id.slice(0, 128);
    throw new SqueHubApiError(response.status, error.code.slice(0, 128),
      error.message.slice(0, 1024), error.details, requestId, safeHeaders(response.headers));
  };
}
TS
            . "\n";
    }

    private function javaScriptRuntime(): string
    {
        return self::MARKER . "\n" . <<<'JS'
import { SqueHubApiError, SqueHubProtocolError, SqueHubTransportError } from "./errors.js";

/** @typedef {string | (() => string | null | undefined | Promise<string | null | undefined>)} TokenProvider */
/** @typedef {{baseUrl: string, fetch?: typeof globalThis.fetch, token?: TokenProvider,
 * credentials?: RequestCredentials, csrfToken?: TokenProvider, csrfHeader?: string}} ClientOptions */
/** @typedef {string | number | boolean} Scalar */
/** @typedef {{name: string, required: boolean, fixed?: Scalar}} ParameterSpec */
/** @typedef {{status: number, body: boolean, contentType: string | null}} SuccessSpec */
/** @typedef {{method: string, path: string, security: 'none'|'pat'|'session',
 * pathParams: ParameterSpec[], query: ParameterSpec[], headers: ParameterSpec[],
 * body: boolean, bodyRequired: boolean, requestContentType: string|null, accept: string,
 * success: SuccessSpec[]}} OperationSpec */
/** @typedef {{path?: Record<string,Scalar>, query?: Record<string,Scalar>,
 * headers?: Record<string,Scalar>, body?: unknown}} RequestArgs */

const SAFE_RESPONSE_HEADERS = ["retry-after", "x-ratelimit-limit", "x-ratelimit-remaining",
  "x-ratelimit-reset", "x-request-id", "allow"];
const HEADER_NAME = /^[!#$%&'*+.^_`|~0-9A-Za-z-]+$/;

/** @param {unknown} value */
function scalar(value) {
  if (typeof value !== "string" && typeof value !== "number" && typeof value !== "boolean") {
    throw new SqueHubProtocolError("An API parameter must be a scalar value.");
  }
  if (typeof value === "number" && !Number.isFinite(value)) {
    throw new SqueHubProtocolError("An API number must be finite.");
  }
  return String(value);
}

/** @param {Record<string,Scalar>|undefined} group @param {string} name */
function ownValue(group, name) {
  return group && Object.prototype.hasOwnProperty.call(group, name) ? group[name] : undefined;
}

/** @param {unknown} value */
function headerValue(value) {
  const result = scalar(value);
  if (/[\r\n\0]/.test(result)) throw new SqueHubProtocolError("An API header value is invalid.");
  return result;
}

/** @param {unknown} value */
function pathSegment(value) {
  const segment = scalar(value);
  if (segment === "" || segment === "." || segment === ".."
    || /[\/\\\x00-\x1F\x7F]/.test(segment)) {
    throw new SqueHubProtocolError("A path parameter is not a valid route segment.");
  }
  try { return encodeURIComponent(segment); }
  catch { throw new SqueHubProtocolError("A path parameter cannot be encoded."); }
}

/** @param {unknown} value @param {WeakSet<object>} seen @param {number} [depth] */
function jsonValue(value, seen, depth = 0) {
  if (depth > 64) throw new SqueHubProtocolError("The JSON request body is too deeply nested.");
  if (value === null || typeof value === "string" || typeof value === "boolean") return;
  if (typeof value === "number" && Number.isFinite(value)) return;
  if (Array.isArray(value)) {
    if (seen.has(value)) throw new SqueHubProtocolError("The JSON request body is cyclic.");
    seen.add(value);
    for (const item of value) jsonValue(item, seen, depth + 1);
    seen.delete(value);
    return;
  }
  if (typeof value === "object" && value !== null
    && (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null)) {
    if (seen.has(value)) throw new SqueHubProtocolError("The JSON request body is cyclic.");
    seen.add(value);
    // Match JSON.stringify's omission of undefined object properties.
    for (const item of Object.values(value)) {
      if (item !== undefined) jsonValue(item, seen, depth + 1);
    }
    seen.delete(value);
    return;
  }
  throw new SqueHubProtocolError("The request body must contain JSON values only.");
}

/** @param {TokenProvider|undefined} provider @returns {Promise<string|null>} */
async function resolveToken(provider) {
  let value;
  try { value = typeof provider === "function" ? await provider() : provider; }
  catch { throw new SqueHubProtocolError("A runtime credential could not be resolved."); }
  if (value === null || value === undefined) return null;
  if (typeof value !== "string" || value === "" || /[\r\n\0]/.test(value)) {
    throw new SqueHubProtocolError("A runtime credential is invalid.");
  }
  return value;
}

/** @param {Headers} headers */
function safeHeaders(headers) {
  /** @type {Record<string,string>} */
  const result = {};
  for (const name of SAFE_RESPONSE_HEADERS) {
    const value = headers.get(name);
    if (value !== null) result[name] = value.slice(0, 256);
  }
  return Object.freeze(result);
}

/** @param {string|null} contentType */
function jsonMediaType(contentType) {
  if (contentType === null) return false;
  const type = contentType.split(";", 1)[0].trim().toLowerCase();
  return type === "application/json"
    || /^application\/[a-z0-9!#$&^_.+-]+\+json$/.test(type);
}

/** @param {string|null} contentType @param {string|null} declared */
function declaredJsonMediaType(contentType, declared) {
  return jsonMediaType(contentType) && contentType.split(";", 1)[0].trim().toLowerCase()
    === declared?.toLowerCase();
}

/** @param {OperationSpec} spec @param {RequestArgs} args */
function validateArguments(spec, args) {
  if (args === null || typeof args !== "object" || Array.isArray(args)) {
    throw new SqueHubProtocolError("API arguments must be an object.");
  }
  for (const name of Object.keys(args)) {
    if (!["path", "query", "headers", "body"].includes(name)) {
      throw new SqueHubProtocolError("An API argument group is unknown.");
    }
  }
  const groups = [
    ["path", spec.pathParams], ["query", spec.query], ["headers", spec.headers],
  ];
  for (const [name, parameters] of groups) {
    const values = args[name];
    if (values === undefined) continue;
    if (values === null || typeof values !== "object" || Array.isArray(values)
      || ![Object.prototype, null].includes(Object.getPrototypeOf(values))) {
      throw new SqueHubProtocolError("API parameters must be keyed objects.");
    }
    for (const key of Object.keys(values)) {
      const parameter = parameters.find(item => item.name === key);
      if (!parameter) throw new SqueHubProtocolError("An API parameter is undeclared.");
      if (parameter.fixed !== undefined && values[key] !== parameter.fixed) {
        throw new SqueHubProtocolError("An API parameter conflicts with the contract.");
      }
    }
  }
  if (!spec.body && Object.prototype.hasOwnProperty.call(args, "body")) {
    throw new SqueHubProtocolError("This API operation has no request body.");
  }
}

/** @param {ClientOptions} options */
export function createRequester(options) {
  if (!options || typeof options.baseUrl !== "string") {
    throw new SqueHubProtocolError("A base URL is required.");
  }
  let base;
  try { base = new URL(options.baseUrl); }
  catch { throw new SqueHubProtocolError("The base URL is invalid."); }
  if (!/^https?:$/.test(base.protocol) || base.username || base.password
    || /[?#]/.test(options.baseUrl) || base.search || base.hash) {
    throw new SqueHubProtocolError("The base URL must be an HTTP URL without credentials, query, or fragment.");
  }
  const fetcher = options.fetch ?? globalThis.fetch?.bind(globalThis);
  if (typeof fetcher !== "function") throw new SqueHubProtocolError("A Fetch implementation is required.");
  const baseUrl = base.href.replace(/\/+$/, "");
  const csrfHeader = options.csrfHeader ?? "X-CSRF-Token";
  if (!HEADER_NAME.test(csrfHeader) || /^(authorization|cookie|content-length|host)$/i.test(csrfHeader)) {
    throw new SqueHubProtocolError("The CSRF header name is invalid.");
  }

  /** @param {OperationSpec} spec @param {RequestArgs} [args] */
  return async (spec, args = {}) => {
    validateArguments(spec, args);
    let path = spec.path;
    for (const parameter of spec.pathParams) {
      const value = parameter.fixed ?? ownValue(args.path, parameter.name);
      if (value === undefined || value === null) {
        throw new SqueHubProtocolError("A required path parameter is missing.");
      }
      path = path.replace("{" + parameter.name + "}", pathSegment(value));
    }
    const url = new URL(baseUrl + (path.startsWith("/") ? path : "/" + path));
    for (const parameter of spec.query) {
      const value = parameter.fixed ?? ownValue(args.query, parameter.name);
      if (value === undefined) {
        if (parameter.required) throw new SqueHubProtocolError("A required query parameter is missing.");
        continue;
      }
      if (value === null) throw new SqueHubProtocolError("A query parameter cannot be null.");
      url.searchParams.append(parameter.name, scalar(value));
    }
    const headers = new Headers({ Accept: spec.accept });
    for (const parameter of spec.headers) {
      const value = parameter.fixed ?? ownValue(args.headers, parameter.name);
      if (value === undefined) {
        if (parameter.required) throw new SqueHubProtocolError("A required header parameter is missing.");
        continue;
      }
      headers.set(parameter.name, headerValue(value));
    }
    if (spec.security === "pat") {
      const token = await resolveToken(options.token);
      if (token !== null) headers.set("Authorization", "Bearer " + token);
    }
    if (spec.security === "session" && !/^(GET|HEAD|OPTIONS)$/i.test(spec.method)) {
      const csrf = await resolveToken(options.csrfToken);
      if (csrf !== null) headers.set(csrfHeader, csrf);
    }
    let body;
    if (spec.body) {
      if (!Object.prototype.hasOwnProperty.call(args, "body")) {
        if (spec.bodyRequired) throw new SqueHubProtocolError("A required JSON request body is missing.");
      } else {
        try {
          jsonValue(args.body, new WeakSet());
          body = JSON.stringify(args.body);
        } catch (error) {
          if (error instanceof SqueHubProtocolError) throw error;
          throw new SqueHubProtocolError("The JSON request body could not be serialized.");
        }
        if (body === undefined) throw new SqueHubProtocolError("The JSON request body is invalid.");
        headers.set("Content-Type", spec.requestContentType ?? "application/json");
      }
    }
    let response;
    try {
      response = await fetcher(url.toString(), {
        method: spec.method, headers, body,
        credentials: spec.security === "session" ? (options.credentials ?? "same-origin") : "omit",
      });
    } catch {
      throw new SqueHubTransportError();
    }
    const declared = spec.success.find(item => item.status === response.status);
    if (declared) {
      if (!declared.body) return undefined;
      if (!declaredJsonMediaType(response.headers.get("content-type"), declared.contentType)) {
        throw new SqueHubProtocolError("The API success response is not JSON.", response.status);
      }
      try { return await response.json(); }
      catch { throw new SqueHubProtocolError("The API success response contains invalid JSON.", response.status); }
    }
    if (response.status >= 200 && response.status < 300) {
      throw new SqueHubProtocolError("The API returned an undeclared success status.", response.status);
    }
    if (!jsonMediaType(response.headers.get("content-type"))) {
      throw new SqueHubProtocolError("The API error response is not JSON.", response.status);
    }
    let payload;
    try { payload = await response.json(); }
    catch { throw new SqueHubProtocolError("The API error response contains invalid JSON.", response.status); }
    if (!payload || typeof payload !== "object" || !("error" in payload)
      || !payload.error || typeof payload.error !== "object"
      || typeof payload.error.code !== "string" || typeof payload.error.message !== "string"
      || typeof payload.request_id !== "string") {
      throw new SqueHubProtocolError("The API returned an unknown error response.", response.status);
    }
    const requestId = payload.request_id.slice(0, 128);
    throw new SqueHubApiError(response.status, payload.error.code.slice(0, 128),
      payload.error.message.slice(0, 1024), payload.error.details, requestId, safeHeaders(response.headers));
  };
}
JS
            . "\n";
    }
}
