<?php

declare(strict_types=1);

namespace App\Api\Sdk\Emitters;

use App\Api\Sdk\SdkException;
use App\Api\Sdk\SdkModel;

/**
 * Emits a standalone PHP 8.2 client from the validated SqueHub SDK model.
 * Generated sources have no framework dependency and receive credentials only
 * at runtime. The output map is deterministic and contains no machine state.
 */
final class PhpEmitter
{
    private const MARKER = '// Generated by SqueHub. Do not edit directly.';
    private const NAMESPACE = 'SqueHubGenerated';
    private const PHP_RESERVED = [
        'abstract', 'and', 'array', 'as', 'break', 'callable', 'case', 'catch',
        'class', 'clone', 'const', 'continue', 'declare', 'default', 'do', 'echo',
        'else', 'elseif', 'empty', 'enddeclare', 'endfor', 'endforeach', 'endif',
        'endswitch', 'endwhile', 'enum', 'eval', 'exit', 'extends', 'false', 'final',
        'finally', 'fn', 'for', 'foreach', 'function', 'global', 'goto', 'if',
        'implements', 'include', 'instanceof', 'insteadof', 'interface', 'isset',
        'list', 'match', 'namespace', 'new', 'null', 'or', 'parent', 'print',
        'private', 'protected', 'public', 'readonly', 'require', 'return', 'self',
        'static', 'switch', 'throw', 'trait', 'true', 'try', 'unset', 'use', 'var',
        'while', 'xor', 'yield',
    ];

    /** @return array<string,string> Relative file names and complete source bytes. */
    public function emit(SdkModel $model): array
    {
        $files = [
            'autoload.php' => $this->autoload(),
            'composer.json' => $this->composer(),
            'src/ApiException.php' => $this->apiException(),
            'src/Client.php' => $this->client($model),
            'src/CurlTransport.php' => $this->curlTransport(),
            'src/HttpResponse.php' => $this->httpResponse(),
            'src/HttpResult.php' => $this->httpResult(),
            'src/Page.php' => $this->page(),
            'src/ProtocolException.php' => $this->protocolException(),
            'src/Runtime.php' => $this->runtime(),
            'src/SchemaMap.php' => $this->schemaMap($model),
            'src/Shape.php' => $this->shape(),
            'src/Transport.php' => $this->transport(),
            'src/TransportException.php' => $this->transportException(),
        ];
        $seen = [];
        foreach ($model->schemas as $name => $schema) {
            $symbol = $model->schemaSymbols[$name];
            if (!$this->isDto($schema)) continue;
            if (in_array(strtolower($symbol), self::PHP_RESERVED, true)) {
                throw new SdkException('Schema ' . $name . ' is a reserved PHP class name.');
            }
            if (isset($seen[strtolower($symbol)])) {
                throw new SdkException('Generated PHP model names collide.');
            }
            $seen[strtolower($symbol)] = true;
            $files['src/Model/' . $symbol . '.php'] = $this->dto($name, $schema, $model);
        }
        ksort($files, SORT_STRING);
        return $files;
    }

    private static function header(string $namespace = self::NAMESPACE): string
    {
        return "<?php\n" . self::MARKER . "\n\ndeclare(strict_types=1);\n\nnamespace "
            . $namespace . ";\n\n";
    }

    private static function literal(mixed $value): string
    {
        return var_export($value, true);
    }

    private function composer(): string
    {
        return "{\n"
            . "  \"name\": \"squehub/generated-sdk\",\n"
            . "  \"description\": \"Generated client for a SqueHub application API\",\n"
            . "  \"type\": \"library\",\n"
            . "  \"require\": {\"php\": \"^8.2\"},\n"
            . "  \"autoload\": {\"psr-4\": {\"SqueHubGenerated\\\\\": \"src/\"}}\n"
            . "}\n";
    }

    private function autoload(): string
    {
        return "<?php\n" . self::MARKER . "\n\ndeclare(strict_types=1);\n\n"
            . <<<'PHP'
spl_autoload_register(static function (string $class): void {
    $prefix = 'SqueHubGenerated\\';
    if (!str_starts_with($class, $prefix)) return;
    $relative = substr($class, strlen($prefix));
    if ($relative === '' || str_contains($relative, '..')) return;
    $file = __DIR__ . '/src/' . str_replace('\\', '/', $relative) . '.php';
    if (is_file($file)) require $file;
});
PHP
            . "\n";
    }

    private function schemaMap(SdkModel $model): string
    {
        return self::header() . "/** Named public schemas from this generated contract. */\n"
            . "final class SchemaMap\n{\n"
            . "    public const SCHEMAS = " . self::literal($model->schemas) . ";\n"
            . "}\n";
    }

    /** @param array<string,mixed>|bool $schema */
    private function isDto(array|bool $schema): bool
    {
        return is_array($schema) && !$this->isPage($schema)
            && ($schema['type'] ?? null) === 'object'
            && isset($schema['properties']) && is_array($schema['properties']);
    }

    /** @param array<string,mixed> $operation */
    private function operationSpec(array $operation): array
    {
        $groups = ['path' => [], 'query' => [], 'header' => []];
        foreach ($operation['parameters'] as $parameter) {
            $entry = ['name' => $parameter['name'], 'required' => $parameter['required'],
                'schema' => $parameter['schema']];
            if (is_array($parameter['schema']) && array_key_exists('const', $parameter['schema'])) {
                $entry['fixed'] = $parameter['schema']['const'];
            }
            $groups[$parameter['in']][] = $entry;
        }
        $success = [];
        foreach ($operation['responses'] as $status => $response) {
            if ((int) $status < 200 || (int) $status > 299) continue;
            $success[(int) $status] = [
                'schema' => $response['schema'], 'content_type' => $response['content_type'],
            ];
        }
        ksort($success, SORT_NUMERIC);
        $accepted = [];
        foreach ($success as $response) {
            $mediaType = $response['content_type'];
            if ($mediaType !== null) $accepted[strtolower($mediaType)] = $mediaType;
        }
        $accepted['application/json'] = 'application/json';
        return [
            'method' => $operation['method'], 'path' => $operation['path'],
            'security' => $operation['security']['type'],
            'accept' => implode(', ', array_values($accepted)),
            'path_params' => $groups['path'], 'query' => $groups['query'],
            'headers' => $groups['header'],
            'body' => $operation['request_body'] !== null,
            'body_required' => $operation['request_body']['required'] ?? false,
            'body_schema' => $operation['request_body']['schema'] ?? null,
            'request_content_type' => $operation['request_body']['content_type'] ?? null,
            'success' => $success,
        ];
    }

    private function client(SdkModel $model): string
    {
        $lines = [self::header(), "/** Public methods map one-to-one to stable operation IDs. */",
            'final class Client', '{', '    private Runtime $runtime;', '',
            '    /** Runtime credentials are never generated into source files. */',
            '    public function __construct(string $baseUrl, ?Transport $transport = null,',
            '        ?callable $tokenProvider = null, ?callable $sessionCookieProvider = null,',
            "        ?callable \$csrfTokenProvider = null, string \$csrfHeader = 'X-CSRF-Token')",
            '    {',
            '        $this->runtime = new Runtime($baseUrl, $transport ?? new CurlTransport(),',
            '            $tokenProvider, $sessionCookieProvider, $csrfTokenProvider, $csrfHeader);',
            '    }'];
        foreach ($model->operations as $operation) {
            $symbol = $operation['symbol'];
            $method = lcfirst($symbol);
            if (in_array(strtolower($method), self::PHP_RESERVED, true)) {
                throw new SdkException('Operation ' . $operation['operation_id']
                    . ' cannot be a PHP method name.');
            }
            $spec = $this->operationSpec($operation);
            $types = [];
            $expressions = [];
            foreach ($spec['success'] as $status => $response) {
                if ($response['schema'] === null) {
                    $types[] = 'null';
                    $expressions[$status] = 'null';
                } else {
                    $types[] = $this->nativeType($response['schema'], $model);
                    $expressions[$status] = $this->hydrate('$result->data', $response['schema'], $model);
                }
            }
            $native = $this->unionType($types);
            $void = $native === 'null';
            $doc = implode('|', array_unique(array_map(fn (array $r): string =>
                $r['schema'] === null ? ($void ? 'void' : 'null')
                    : $this->docType($r['schema'], $model),
                $spec['success'])));
            $lines[] = '';
            $lines[] = '    /**';
            $lines[] = '     * ' . $operation['operation_id'] . ' (' . $operation['method']
                . ' ' . $operation['path'] . ').';
            $lines[] = '     * @param array{path?:array<string,mixed>,query?:array<string,mixed>,'
                . 'headers?:array<string,mixed>,body?:mixed} $args';
            $lines[] = '     * @return ' . $doc;
            $lines[] = '     */';
            $lines[] = '    public function ' . $method . '(array $args = []): ' . ($void ? 'void' : $native);
            $lines[] = '    {';
            $lines[] = '        $result = $this->runtime->send(' . self::literal($spec) . ', $args);';
            if (!$void) {
                $lines[] = '        return match ($result->status) {';
                foreach ($expressions as $status => $expression) {
                    $lines[] = '            ' . $status . ' => ' . $expression . ',';
                }
                $lines[] = "            default => throw new ProtocolException('The API returned an undeclared success status.'),";
                $lines[] = '        };';
            }
            $lines[] = '    }';
        }
        $lines[] = '}';
        return implode("\n", $lines) . "\n";
    }

    /** @param array<string,mixed>|bool $schema */
    private function hydrate(string $expression, array|bool $schema, SdkModel $model,
        array $trail = []): string
    {
        if (!is_array($schema)) return $expression;
        if (isset($schema['$ref'])) {
            $name = substr($schema['$ref'], strlen('#/components/schemas/'));
            if (isset($trail[$name])) return $expression;
            $trail[$name] = true;
            if ($this->isPage($model->schemas[$name])) {
                return $this->hydrate($expression, $model->schemas[$name], $model, $trail);
            }
            if ($this->isDto($model->schemas[$name])) {
                return '\\' . self::NAMESPACE . '\\Model\\'
                    . $model->schemaSymbols[$name] . '::fromValue(' . $expression . ')';
            }
            return $this->hydrate($expression, $model->schemas[$name], $model, $trail);
        }
        if (isset($schema['oneOf']) || isset($schema['anyOf'])) {
            $branches = $schema['oneOf'] ?? $schema['anyOf'];
            $result = "throw new ProtocolException()";
            foreach (array_reverse($branches) as $branch) {
                $result = '(Shape::matches(' . $expression . ', '
                    . self::literal($branch) . ') ? '
                    . $this->hydrate($expression, $branch, $model, $trail) . ' : ' . $result . ')';
            }
            return $result;
        }
        if (($schema['type'] ?? null) === 'array' && isset($schema['items'])) {
            $item = $this->hydrate('$item', $schema['items'], $model, $trail);
            if ($item !== '$item') {
                return 'array_map(static fn (mixed $item): mixed => ' . $item
                    . ', (array) ' . $expression . ')';
            }
        }
        if ($this->isPage($schema)) {
            $item = $this->hydrate('$item', $schema['properties']['data']['items'], $model, $trail);
            return 'Page::fromValue(' . $expression . ', static fn (mixed $item): mixed => '
                . $item . ')';
        }
        if (($schema['type'] ?? null) === 'object') {
            // Inline objects remain associative values; named schemas alone
            // receive a stable DTO class in the generated package.
            return 'Shape::toArray(' . $expression . ')';
        }
        if (is_array($schema['type'] ?? null)
            && in_array('object', $schema['type'], true)) {
            return '(' . $expression . ' instanceof \\stdClass ? Shape::toArray('
                . $expression . ') : ' . $expression . ')';
        }
        return $expression;
    }

    private function isPage(array $schema): bool
    {
        $required = $schema['required'] ?? [];
        sort($required, SORT_STRING);
        return ($schema['type'] ?? null) === 'object'
            && array_keys($schema['properties'] ?? []) === ['data', 'meta']
            && $required === ['data', 'meta']
            && (($schema['properties']['data']['type'] ?? null) === 'array')
            && isset($schema['properties']['data']['items'])
            && (($schema['properties']['meta']['$ref'] ?? null)
                === '#/components/schemas/SqueHubPaginationMeta');
    }

    /** @param array<string,mixed>|bool $schema */
    private function nativeType(array|bool $schema, SdkModel $model, array $trail = []): string
    {
        if (is_bool($schema)) return 'mixed';
        if (isset($schema['$ref'])) {
            $name = substr($schema['$ref'], strlen('#/components/schemas/'));
            if (isset($trail[$name])) return 'mixed';
            $trail[$name] = true;
            if ($this->isPage($model->schemas[$name])) return 'Page';
            return $this->isDto($model->schemas[$name])
                ? 'Model\\' . $model->schemaSymbols[$name]
                : $this->nativeType($model->schemas[$name], $model, $trail);
        }
        if ($this->isPage($schema)) return 'Page';
        if (isset($schema['oneOf']) || isset($schema['anyOf'])) {
            $parts = $schema['oneOf'] ?? $schema['anyOf'];
            return $this->unionType(array_map(fn ($part): string => $this->nativeType($part, $model, $trail),
                $parts));
        }
        if (isset($schema['allOf'])) return 'mixed';
        $types = $schema['type'] ?? null;
        if ($types === null && isset($schema['enum'])) {
            $types = array_values(array_unique(array_map(static fn ($v): string => get_debug_type($v),
                $schema['enum'])));
        }
        if ($types === null) return 'mixed';
        $parts = [];
        foreach ((array) $types as $type) {
            $parts[] = match ($type) {
                'string' => 'string', 'integer', 'int' => 'int',
                'number', 'float' => 'float', 'boolean', 'bool' => 'bool',
                'array', 'object' => 'array', 'null' => 'null', default => 'mixed',
            };
        }
        return $this->unionType($parts);
    }

    /** @param array<string,mixed>|bool $schema */
    private function docType(array|bool $schema, SdkModel $model, array $trail = []): string
    {
        if (!is_array($schema)) return 'mixed';
        if (isset($schema['$ref'])) {
            $name = substr($schema['$ref'], strlen('#/components/schemas/'));
            if (isset($trail[$name])) return 'mixed';
            $trail[$name] = true;
            if ($this->isPage($model->schemas[$name])) {
                return $this->docType($model->schemas[$name], $model, $trail);
            }
            return $this->isDto($model->schemas[$name])
                ? 'Model\\' . $model->schemaSymbols[$name]
                : $this->docType($model->schemas[$name], $model, $trail);
        }
        if ($this->isPage($schema)) {
            return 'Page<' . $this->docType($schema['properties']['data']['items'], $model, $trail) . '>';
        }
        if (($schema['type'] ?? null) === 'array') {
            return 'list<' . $this->docType($schema['items'] ?? true, $model, $trail) . '>';
        }
        if (($schema['type'] ?? null) === 'object') return 'array<string,mixed>';
        return $this->nativeType($schema, $model);
    }

    /** @param list<string> $types */
    private function unionType(array $types): string
    {
        $types = array_values(array_unique(array_merge(...array_map(
            static fn (string $type): array => explode('|', $type), $types))));
        if (in_array('mixed', $types, true)) return 'mixed';
        if (in_array('float', $types, true) && in_array('int', $types, true)) {
            $types = array_values(array_diff($types, ['int']));
        }
        sort($types, SORT_STRING);
        return implode('|', $types);
    }

    private function transport(): string
    {
        return self::header() . <<<'PHP'
/** A small HTTP boundary so consumers can substitute their own transport. */
interface Transport
{
    /** @param array<string,string> $headers */
    public function send(string $method, string $url, array $headers, ?string $body): HttpResponse;
}
PHP
            . "\n";
    }

    private function httpResponse(): string
    {
        return self::header() . <<<'PHP'
/** Transport result; header lookup is case-insensitive. */
final readonly class HttpResponse
{
    /** @param array<string,string> $headers */
    public function __construct(
        public int $status,
        public array $headers,
        public string $body,
    ) {
        if ($status < 100 || $status > 599) {
            throw new TransportException();
        }
    }

    public function header(string $name): ?string
    {
        foreach ($this->headers as $key => $value) {
            if (strcasecmp($key, $name) === 0) return $value;
        }
        return null;
    }
}
PHP
            . "\n";
    }

    private function httpResult(): string
    {
        return self::header() . <<<'PHP'
/** A validated success response before operation-specific hydration. */
final readonly class HttpResult
{
    public function __construct(public int $status, public mixed $data)
    {
    }
}
PHP
            . "\n";
    }

    private function curlTransport(): string
    {
        return self::header() . <<<'PHP'
/**
 * One cURL request per operation. Redirects are disabled so credentials are
 * never forwarded to a different origin by the generated transport.
 */
final class CurlTransport implements Transport
{
    public function send(string $method, string $url, array $headers, ?string $body): HttpResponse
    {
        if (!function_exists('curl_init')) throw new TransportException();
        $handle = curl_init($url);
        if ($handle === false) throw new TransportException();
        $responseHeaders = [];
        $headerLines = [];
        foreach ($headers as $name => $value) $headerLines[] = $name . ': ' . $value;
        try {
            $options = [
                CURLOPT_CUSTOMREQUEST => $method,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_FOLLOWLOCATION => false,
                CURLOPT_CONNECTTIMEOUT => 10,
                CURLOPT_TIMEOUT => 30,
                CURLOPT_HTTPHEADER => $headerLines,
                CURLOPT_HEADERFUNCTION => static function ($unused, string $line) use (&$responseHeaders): int {
                    $length = strlen($line);
                    if (preg_match('/^HTTP\/\S+\s+[1-5][0-9]{2}/i', $line) === 1) {
                        $responseHeaders = [];
                    } else {
                        $colon = strpos($line, ':');
                        if ($colon !== false) {
                            $name = trim(substr($line, 0, $colon));
                            if ($name !== '') $responseHeaders[$name] = trim(substr($line, $colon + 1));
                        }
                    }
                    return $length;
                },
            ];
            if ($body !== null) $options[CURLOPT_POSTFIELDS] = $body;
            if (!curl_setopt_array($handle, $options)) throw new TransportException();
            $response = curl_exec($handle);
            if (!is_string($response)) throw new TransportException();
            $status = curl_getinfo($handle, CURLINFO_RESPONSE_CODE);
            if (!is_int($status) || $status < 100 || $status > 599) throw new TransportException();
            return new HttpResponse($status, $responseHeaders, $response);
        } finally {
            curl_close($handle);
        }
    }
}
PHP
            . "\n";
    }

    private function apiException(): string
    {
        return self::header() . <<<'PHP'
use RuntimeException;

/** A declared SqueHub API error. The exception text never includes request data. */
final class ApiException extends RuntimeException
{
    /**
     * @param array<string,string> $safeHeaders
     */
    public function __construct(
        public readonly int $status,
        public readonly string $errorCode,
        public readonly string $apiMessage,
        public readonly mixed $details,
        public readonly string $requestId,
        public readonly array $safeHeaders = [],
    ) {
        parent::__construct('The API returned an error.', $status);
    }
}
PHP
            . "\n";
    }

    private function protocolException(): string
    {
        return self::header() . <<<'PHP'
use RuntimeException;

/** The peer returned data that does not satisfy its published contract. */
final class ProtocolException extends RuntimeException
{
    public function __construct(string $message = 'The API returned an invalid response.')
    {
        parent::__construct($message);
    }
}
PHP
            . "\n";
    }

    private function transportException(): string
    {
        return self::header() . <<<'PHP'
use RuntimeException;

/** A bounded network failure with no URL, request body, or credential data. */
final class TransportException extends RuntimeException
{
    public function __construct()
    {
        parent::__construct('The API request could not be completed.');
    }
}
PHP
            . "\n";
    }

    private function page(): string
    {
        return self::header() . <<<'PHP'
use stdClass;

/**
 * @template T
 * The server's data/meta pagination shape, with hydrated data items.
 */
final readonly class Page
{
    /**
     * @param list<T> $data
     * @param array<string,mixed> $meta
     */
    public function __construct(public array $data, public array $meta)
    {
    }

    /**
     * @template U
     * @param callable(mixed):U $hydrate
     * @return self<U>
     */
    public static function fromValue(mixed $value, callable $hydrate): self
    {
        if (!$value instanceof stdClass || !isset($value->data, $value->meta)
            || !is_array($value->data) || !$value->meta instanceof stdClass) {
            throw new ProtocolException();
        }
        $meta = (array) $value->meta;
        foreach (['page', 'per_page', 'total', 'pages'] as $name) {
            if (!isset($meta[$name]) || !is_int($meta[$name])) throw new ProtocolException();
        }
        foreach (['from', 'to'] as $name) {
            if (!array_key_exists($name, $meta)
                || ($meta[$name] !== null && !is_int($meta[$name]))) throw new ProtocolException();
        }
        foreach (['has_next', 'has_previous'] as $name) {
            if (!isset($meta[$name]) || !is_bool($meta[$name])) throw new ProtocolException();
        }
        return new self(array_map($hydrate, $value->data), $meta);
    }
}
PHP
            . "\n";
    }

    private function shape(): string
    {
        return self::header() . <<<'PHP'
use stdClass;

/**
 * Bounded structural checking at the generated client boundary. It checks
 * declared types, required/nullable fields, references and compositions;
 * failures are intentionally generic so server values never enter exceptions.
 */
final class Shape
{
    /** Convert inline JSON objects without leaving nested stdClass values. */
    public static function toArray(mixed $value, int $depth = 0): array
    {
        if ($depth > 64 || (!is_array($value) && !$value instanceof stdClass)) {
            throw new ProtocolException();
        }
        $result = (array) $value;
        foreach ($result as $name => $child) {
            if (is_array($child) || $child instanceof stdClass) {
                $result[$name] = self::toArray($child, $depth + 1);
            }
        }
        return $result;
    }

    public static function matches(mixed $value, array|bool $schema): bool
    {
        try {
            self::assert($value, $schema);
            return true;
        } catch (ProtocolException) {
            return false;
        }
    }

    public static function assert(mixed $value, array|bool $schema, bool $response = true,
        int $depth = 0): void
    {
        if ($depth > 64 || $schema === false) throw new ProtocolException();
        if ($schema === true) return;
        if (isset($schema['$ref'])) {
            $name = substr((string) $schema['$ref'], strlen('#/components/schemas/'));
            $target = SchemaMap::SCHEMAS[$name] ?? null;
            if ($target === null) throw new ProtocolException();
            self::assert($value, $target, $response, $depth + 1);
            return;
        }
        foreach (['allOf', 'anyOf', 'oneOf'] as $composition) {
            if (!isset($schema[$composition])) continue;
            $matches = 0;
            foreach ($schema[$composition] as $part) {
                try {
                    self::assert($value, $part, $response, $depth + 1);
                    ++$matches;
                } catch (ProtocolException) {
                    // A failed branch is expected for union and intersection evaluation.
                }
            }
            if (($composition === 'allOf' && $matches !== count($schema[$composition]))
                || ($composition === 'anyOf' && $matches === 0)
                || ($composition === 'oneOf' && $matches !== 1)) {
                throw new ProtocolException();
            }
        }
        if (array_key_exists('const', $schema) && !self::sameJson($value, $schema['const'])) {
            throw new ProtocolException();
        }
        if (isset($schema['enum'])) {
            $matched = false;
            foreach ($schema['enum'] as $choice) {
                if (self::sameJson($value, $choice)) { $matched = true; break; }
            }
            if (!$matched) throw new ProtocolException();
        }
        $types = $schema['type'] ?? null;
        if ($types === null) return;
        $types = (array) $types;
        $actual = self::type($value);
        if (!in_array($actual, $types, true)
            && !($actual === 'integer' && in_array('number', $types, true))) {
            throw new ProtocolException();
        }
        if ($actual === 'object') {
            $object = $value instanceof stdClass ? (array) $value : $value;
            $properties = $schema['properties'] ?? [];
            foreach ($schema['required'] ?? [] as $name) {
                $property = $properties[$name] ?? [];
                if (($response && ($property['writeOnly'] ?? false))
                    || (!$response && ($property['readOnly'] ?? false))) continue;
                if (!array_key_exists($name, $object)) throw new ProtocolException();
            }
            foreach ($object as $name => $child) {
                if (array_key_exists($name, $properties)) {
                    $property = $properties[$name];
                    if (($response && ($property['writeOnly'] ?? false))
                        || (!$response && ($property['readOnly'] ?? false))) {
                        throw new ProtocolException();
                    }
                    self::assert($child, $property, $response, $depth + 1);
                } elseif (($schema['additionalProperties'] ?? true) === false) {
                    throw new ProtocolException();
                } elseif (is_array($schema['additionalProperties'] ?? null)
                    || is_bool($schema['additionalProperties'] ?? null)) {
                    self::assert($child, $schema['additionalProperties'], $response, $depth + 1);
                }
            }
        } elseif ($actual === 'array') {
            $count = count($value);
            if (isset($schema['minItems']) && $count < $schema['minItems']) throw new ProtocolException();
            if (isset($schema['maxItems']) && $count > $schema['maxItems']) throw new ProtocolException();
            foreach ($value as $child) {
                if (isset($schema['items'])) self::assert($child, $schema['items'], $response, $depth + 1);
            }
            if (($schema['uniqueItems'] ?? false) === true) {
                $encoded = array_map(static fn (mixed $item): string =>
                    json_encode($item, JSON_THROW_ON_ERROR), $value);
                if (count(array_unique($encoded)) !== $count) throw new ProtocolException();
            }
        } elseif ($actual === 'string') {
            if (isset($schema['minLength']) || isset($schema['maxLength'])) {
                $length = preg_match_all('/./us', $value);
                if ($length === false) throw new ProtocolException();
                if (isset($schema['minLength']) && $length < $schema['minLength']) throw new ProtocolException();
                if (isset($schema['maxLength']) && $length > $schema['maxLength']) throw new ProtocolException();
            }
            if (isset($schema['pattern'])) {
                $pattern = '~' . str_replace('~', '\~', $schema['pattern']) . '~u';
                if (@preg_match($pattern, $value) !== 1) throw new ProtocolException();
            }
        } elseif ($actual === 'integer' || $actual === 'number') {
            if (isset($schema['minimum']) && $value < $schema['minimum']) throw new ProtocolException();
            if (isset($schema['maximum']) && $value > $schema['maximum']) throw new ProtocolException();
            if (isset($schema['exclusiveMinimum']) && $value <= $schema['exclusiveMinimum']) throw new ProtocolException();
            if (isset($schema['exclusiveMaximum']) && $value >= $schema['exclusiveMaximum']) throw new ProtocolException();
        }
    }

    private static function type(mixed $value): string
    {
        return match (true) {
            $value === null => 'null',
            is_bool($value) => 'boolean',
            is_int($value) => 'integer',
            is_float($value) => 'number',
            is_string($value) => 'string',
            $value instanceof stdClass => 'object',
            is_array($value) && array_is_list($value) => 'array',
            is_array($value) => 'object',
            default => 'invalid',
        };
    }

    private static function sameJson(mixed $left, mixed $right): bool
    {
        try {
            return json_encode(self::canonical($left), JSON_THROW_ON_ERROR)
                === json_encode(self::canonical($right), JSON_THROW_ON_ERROR);
        } catch (\JsonException) {
            throw new ProtocolException();
        }
    }

    /** JSON object member order is insignificant for enum and const checks. */
    private static function canonical(mixed $value, int $depth = 0): mixed
    {
        if ($depth > 64) throw new ProtocolException();
        if ($value instanceof stdClass || (is_array($value) && !array_is_list($value))) {
            $properties = (array) $value;
            ksort($properties, SORT_STRING);
            $object = new stdClass();
            foreach ($properties as $name => $child) {
                $object->{(string) $name} = self::canonical($child, $depth + 1);
            }
            return $object;
        }
        if (is_array($value)) {
            return array_map(static fn (mixed $child): mixed => self::canonical($child, $depth + 1),
                $value);
        }
        return $value;
    }
}
PHP
            . "\n";
    }

    private function runtime(): string
    {
        return self::header() . <<<'PHP'
use JsonException;
use stdClass;

/** Shared request and response mechanics; public methods remain operation-specific. */
final class Runtime
{
    private readonly string $baseUrl;

    /** @param callable():string|null $tokenProvider
     *  @param callable():string|null $sessionCookieProvider
     *  @param callable():string|null $csrfTokenProvider
     */
    public function __construct(
        string $baseUrl,
        private readonly Transport $transport,
        private readonly mixed $tokenProvider,
        private readonly mixed $sessionCookieProvider,
        private readonly mixed $csrfTokenProvider,
        private readonly string $csrfHeader,
    ) {
        $parts = parse_url($baseUrl);
        if ($parts === false || !in_array(strtolower($parts['scheme'] ?? ''), ['http', 'https'], true)
            || !isset($parts['host']) || isset($parts['user']) || isset($parts['pass'])
            || isset($parts['query']) || isset($parts['fragment'])) {
            throw new ProtocolException('The API base URL is invalid.');
        }
        if (!self::headerName($csrfHeader)) throw new ProtocolException('The CSRF header name is invalid.');
        $this->baseUrl = rtrim($baseUrl, '/');
    }

    /** @param array<string,mixed> $spec @param array<string,mixed> $args */
    public function send(array $spec, array $args): HttpResult
    {
        foreach (array_keys($args) as $key) {
            if (!in_array($key, ['path', 'query', 'headers', 'body'], true)) {
                throw new ProtocolException('An API argument group is unknown.');
            }
        }
        $path = $spec['path'];
        $query = [];
        $headers = ['Accept' => $spec['accept']];
        foreach (['path' => 'path_params', 'query' => 'query', 'headers' => 'headers'] as $group => $specKey) {
            $values = $args[$group] ?? [];
            if (!is_array($values)) throw new ProtocolException('API arguments must be keyed arrays.');
            $known = array_column($spec[$specKey], 'name');
            foreach ($values as $name => $unused) {
                if (!in_array($name, $known, true)) throw new ProtocolException('An API parameter is undeclared.');
            }
            foreach ($spec[$specKey] as $parameter) {
                $name = $parameter['name'];
                $present = array_key_exists($name, $values);
                if (!$present && array_key_exists('fixed', $parameter)) {
                    $value = $parameter['fixed'];
                    $present = true;
                } else {
                    $value = $present ? $values[$name] : null;
                }
                if (!$present) {
                    if ($parameter['required']) throw new ProtocolException('A required API parameter is missing.');
                    continue;
                }
                if (array_key_exists('fixed', $parameter) && $value !== $parameter['fixed']) {
                    throw new ProtocolException('An API version/header value conflicts with the contract.');
                }
                Shape::assert($value, $parameter['schema'], false);
                if (!is_scalar($value) || $value === '') throw new ProtocolException('An API parameter is not serializable.');
                $text = is_bool($value) ? ($value ? 'true' : 'false') : (string) $value;
                if ($group === 'path') {
                    // Mirror RouteMatcher's decoded-segment safety boundary.
                    if (in_array($text, ['.', '..'], true) || str_contains($text, '/')
                        || str_contains($text, '\\')
                        || preg_match('/[\x00-\x1F\x7F]/', $text) === 1) {
                        throw new ProtocolException('An API path parameter is unsafe.');
                    }
                    $path = str_replace('{' . $name . '}', rawurlencode($text), $path);
                } elseif ($group === 'query') {
                    $query[$name] = $text;
                } else {
                    if (!self::headerName($name) || !self::headerValue($text)) {
                        throw new ProtocolException('An API header is invalid.');
                    }
                    $headers[$name] = $text;
                }
            }
        }
        if (str_contains($path, '{') || str_contains($path, '}')) throw new ProtocolException();
        $url = $this->baseUrl . $path;
        if ($query !== []) $url .= '?' . http_build_query($query, '', '&', PHP_QUERY_RFC3986);
        if (strlen($url) > 16384) throw new ProtocolException('The API URL is too long.');

        $security = $spec['security'];
        if ($security === 'pat') {
            if ($this->tokenProvider !== null) {
                $token = self::resolveCredential($this->tokenProvider);
                if ($token !== null) {
                    if (!is_string($token) || $token === '' || !self::headerValue($token)
                        || preg_match('/\s/', $token) === 1) {
                        throw new ProtocolException('A PAT provider returned an invalid token.');
                    }
                    $headers['Authorization'] = 'Bearer ' . $token;
                }
            }
        } elseif ($security === 'session') {
            if ($this->sessionCookieProvider !== null) {
                $cookie = self::resolveCredential($this->sessionCookieProvider);
                if ($cookie !== null) {
                    if (!is_string($cookie) || $cookie === '' || !self::headerValue($cookie)) {
                        throw new ProtocolException('A Session cookie provider returned an invalid value.');
                    }
                    $headers['Cookie'] = $cookie;
                }
            }
            if (!in_array($spec['method'], ['GET', 'HEAD', 'OPTIONS'], true)
                && $this->csrfTokenProvider !== null) {
                $csrf = self::resolveCredential($this->csrfTokenProvider);
                if ($csrf !== null) {
                    if (!is_string($csrf) || $csrf === '' || !self::headerValue($csrf)) {
                        throw new ProtocolException('A CSRF token provider returned an invalid value.');
                    }
                    $headers[$this->csrfHeader] = $csrf;
                }
            }
        } elseif ($security !== 'none') {
            throw new ProtocolException();
        }

        $body = null;
        if ($spec['body']) {
            if (!array_key_exists('body', $args)) {
                if ($spec['body_required']) throw new ProtocolException('A required API body is missing.');
            } else {
                Shape::assert($args['body'], $spec['body_schema'], false);
                try {
                    $body = json_encode($args['body'], JSON_THROW_ON_ERROR
                        | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
                } catch (JsonException) {
                    throw new ProtocolException('The API body is not JSON serializable.');
                }
                $headers['Content-Type'] = $spec['request_content_type'];
            }
        } elseif (array_key_exists('body', $args)) {
            throw new ProtocolException('This API operation does not declare a body.');
        }

        try {
            $response = $this->transport->send($spec['method'], $url, $headers, $body);
        } catch (\Throwable) {
            // A custom transport must not leak its URL or credential-bearing error text.
            throw new TransportException();
        }
        if ($response->status < 200 || $response->status > 299) {
            $this->throwApiError($response);
        }
        if (!isset($spec['success'][$response->status])) {
            throw new ProtocolException('The API returned an undeclared success status.');
        }
        $declared = $spec['success'][$response->status];
        if ($declared['schema'] === null) return new HttpResult($response->status, null);
        if (!self::declaredJsonMediaType($response->header('Content-Type'),
            $declared['content_type'])) throw new ProtocolException();
        $data = self::decodeJson($response->body);
        Shape::assert($data, $declared['schema']);
        return new HttpResult($response->status, $data);
    }

    private function throwApiError(HttpResponse $response): never
    {
        if (!self::jsonMediaType($response->header('Content-Type'))) throw new ProtocolException();
        $payload = self::decodeJson($response->body);
        if (!$payload instanceof stdClass || !isset($payload->error, $payload->request_id)
            || !$payload->error instanceof stdClass
            || !is_string($payload->error->code ?? null)
            || !is_string($payload->error->message ?? null)
            || !is_string($payload->request_id)) {
            throw new ProtocolException();
        }
        $safeHeaders = [];
        foreach (['Retry-After', 'X-RateLimit-Limit', 'X-RateLimit-Remaining',
            'X-RateLimit-Reset'] as $name) {
            $value = $response->header($name);
            if ($value !== null && preg_match('/\A[0-9]{1,20}\z/D', $value) === 1) {
                $safeHeaders[$name] = $value;
            }
        }
        throw new ApiException($response->status,
            substr($payload->error->code, 0, 128),
            substr($payload->error->message, 0, 1024),
            isset($payload->error->details)
                ? Shape::toArray($payload->error->details) : null,
            substr($payload->request_id, 0, 128),
            $safeHeaders);
    }

    private static function decodeJson(string $body): mixed
    {
        try {
            return json_decode($body, false, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException) {
            throw new ProtocolException();
        }
    }

    private static function resolveCredential(mixed $provider): mixed
    {
        try {
            return $provider();
        } catch (\Throwable) {
            throw new ProtocolException('A runtime credential could not be resolved.');
        }
    }

    private static function jsonMediaType(?string $value): bool
    {
        if ($value === null) return false;
        $type = strtolower(trim(explode(';', $value, 2)[0]));
        return $type === 'application/json'
            || preg_match('~^application/[a-z0-9!#$&^_.+-]+\+json$~', $type) === 1;
    }

    private static function declaredJsonMediaType(?string $actual, ?string $expected): bool
    {
        if (!self::jsonMediaType($actual) || $expected === null) return false;
        return strtolower(trim(explode(';', $actual, 2)[0]))
            === strtolower(trim(explode(';', $expected, 2)[0]));
    }

    private static function headerName(string $name): bool
    {
        return preg_match("/\A[A-Za-z0-9!#$%&'*+.^_\x60|~-]{1,128}\z/D", $name) === 1;
    }

    private static function headerValue(string $value): bool
    {
        return strlen($value) <= 8192 && preg_match('/[\x00-\x1F\x7F]/', $value) !== 1;
    }
}
PHP
            . "\n";
    }

    /** @param array<string,mixed> $schema */
    private function dto(string $name, array $schema, SdkModel $model): string
    {
        $symbol = $model->schemaSymbols[$name];
        $lines = [self::header(self::NAMESPACE . '\\Model'),
            'use ' . self::NAMESPACE . '\\ProtocolException;',
            'use ' . self::NAMESPACE . '\\Shape;',
            'use ' . self::NAMESPACE . '\\Page;',
            'use stdClass;', '',
            '/** Validated response value for the named ' . $name . ' schema. */',
            'final readonly class ' . $symbol,
            '{',
            '    private function __construct(private stdClass $data) {}',
            '',
            '    public static function fromValue(mixed $value): self',
            '    {',
            '        Shape::assert($value, ' . self::literal(['$ref' =>
                '#/components/schemas/' . $name]) . ');',
            '        if (!$value instanceof stdClass) throw new ProtocolException();',
            '        return new self($value);',
            '    }',
            '',
            '    /** @return array<string,mixed> */',
            '    public function toArray(): array { return Shape::toArray($this->data); }',
        ];
        $seen = [];
        foreach ($schema['properties'] as $property => $definition) {
            if (($definition['writeOnly'] ?? false) === true) continue;
            $parts = preg_split('/[^A-Za-z0-9]+/', $property);
            $suffix = implode('', array_map('ucfirst', array_filter($parts,
                static fn (string $part): bool => $part !== '')));
            if ($suffix === '') throw new SdkException('Schema ' . $name
                . ' has a property without a PHP accessor name.');
            $folded = strtolower($suffix);
            if (isset($seen[$folded])) {
                throw new SdkException('Schema ' . $name . ' has colliding PHP property accessors.');
            }
            $seen[$folded] = true;
            $required = in_array($property, $schema['required'] ?? [], true);
            $type = $this->nativeType($definition, $model);
            if (!$required) $type = $this->unionType([$type, 'null']);
            $doc = $this->docType($definition, $model);
            if (!$required && !in_array('null', explode('|', $doc), true)) $doc .= '|null';
            $type = str_replace('Model\\', '\\' . self::NAMESPACE . '\\Model\\', $type);
            $doc = str_replace('Model\\', '\\' . self::NAMESPACE . '\\Model\\', $doc);
            $value = '$this->data->{' . self::literal($property) . '}';
            $hydrated = $this->hydrate($value, $definition, $model);
            $lines[] = '';
            $lines[] = '    /** @return ' . $doc . ' */';
            $lines[] = '    public function get' . $suffix . '(): ' . $type;
            $lines[] = '    {';
            $lines[] = '        return ' . ($required ? $hydrated
                : '$this->has' . $suffix . '() ? ' . $hydrated . ' : null') . ';';
            $lines[] = '    }';
            if (!$required) {
                $lines[] = '';
                $lines[] = '    /** Distinguishes an absent property from an explicit JSON null. */';
                $lines[] = '    public function has' . $suffix . '(): bool';
                $lines[] = '    {';
                $lines[] = '        return property_exists($this->data, ' . self::literal($property) . ');';
                $lines[] = '    }';
            }
        }
        $lines[] = '}';
        return implode("\n", $lines) . "\n";
    }
}
