<?php

declare(strict_types=1);

namespace SqueHub\Tests\Unit\Api;

use App\Api\Sdk\Emitters\JavaScriptEmitter;
use App\Api\Sdk\Emitters\TypeScriptEmitter;
use App\Api\Sdk\SdkModel;
use PHPUnit\Framework\TestCase;

final class SdkEcmaEmitterTest extends TestCase
{
    public function testGeneratedModulesAreStableAndContainNoCredentials(): void
    {
        $model = self::model();
        foreach ([new TypeScriptEmitter(), new JavaScriptEmitter()] as $emitter) {
            $first = $emitter->emit($model);
            self::assertSame($first, $emitter->emit($model));
            foreach ($first as $name => $content) {
                if ($name !== 'package.json') {
                    self::assertStringStartsWith('// Generated by SqueHub. Do not edit directly.', $content);
                }
                self::assertStringNotContainsString('sample-secret', $content);
            }
        }
        $javaScript = (new JavaScriptEmitter())->emit($model);
        self::assertSame("{\n  \"type\": \"module\"\n}\n", $javaScript['package.json']);
        self::assertStringContainsString('this.users = Object.freeze({', $javaScript['client.js']);
    }

    public function testTypeScriptUsesSchemaDirectionalityNullableFieldsAndAllSuccesses(): void
    {
        $files = (new TypeScriptEmitter())->emit(self::model());
        $types = $files['types.ts'];
        self::assertStringContainsString('export type User = { "id": number; "nickname"?: string | null;', $types);
        self::assertStringNotContainsString('"secret": string', explode('export type UserInput', $types)[0]);
        self::assertStringContainsString('export type UserInput = { "nickname"?: string | null; "secret": string;', $types);
        self::assertStringContainsString('SqueHubPage<User>', $types);
        self::assertStringContainsString('export type UsersShowResponse = User | void;', $types);
        self::assertStringContainsString('path: { "id": number }', $types);
        self::assertStringContainsString('encodeURIComponent(segment)', $files['runtime.ts']);
    }

    public function testJavaScriptJSDocPreservesLiteralUnknownEnumValues(): void
    {
        $model = self::model();
        $schemas = $model->schemas;
        $symbols = $model->schemaSymbols;
        $schemas['Status'] = ['enum' => ['unknown']];
        $symbols['Status'] = 'Status';
        $expanded = new SdkModel($model->apiVersion, $schemas, $symbols,
            $model->operations, $model->webhooks, $model->fingerprint);

        $types = (new JavaScriptEmitter())->emit($expanded)['types.js'];
        self::assertStringContainsString('/** @typedef {"unknown"} Status */', $types);
        self::assertStringNotContainsString('/** @typedef {"*"} Status */', $types);
    }

    public function testClosedEmptyObjectDoesNotAcceptArbitraryPrimitives(): void
    {
        $model = self::model();
        $schemas = $model->schemas;
        $symbols = $model->schemaSymbols;
        $schemas['Empty'] = ['type' => 'object', 'properties' => [],
            'additionalProperties' => false];
        $symbols['Empty'] = 'Empty';
        $expanded = new SdkModel($model->apiVersion, $schemas, $symbols,
            $model->operations, $model->webhooks, $model->fingerprint);

        $typescript = (new TypeScriptEmitter())->emit($expanded)['types.ts'];
        self::assertStringContainsString('export type Empty = Record<string, never>;',
            $typescript);
        self::assertStringContainsString('export type EmptyInput = Record<string, never>;',
            $typescript);
    }

    public function testVendorJsonSuccessIsRequestedAlongsideStandardApiErrors(): void
    {
        $model = self::model();
        $operations = $model->operations;
        $operations[0]['responses']['200']['content_type'] = 'application/vnd.squehub+json';
        $expanded = new SdkModel($model->apiVersion, $model->schemas,
            $model->schemaSymbols, $operations, $model->webhooks, $model->fingerprint);

        foreach ([new TypeScriptEmitter(), new JavaScriptEmitter()] as $emitter) {
            $files = $emitter->emit($expanded);
            $client = $files[$emitter instanceof TypeScriptEmitter ? 'client.ts' : 'client.js'];
            self::assertStringContainsString('application/vnd.squehub+json, application/json',
                $client);
        }
    }

    public function testSchemaStringsCannotBreakOutOfGeneratedJavaScriptComments(): void
    {
        $model = self::model();
        $schemas = $model->schemas;
        $symbols = $model->schemaSymbols;
        $schemas['Status'] = ['enum' => ['*/globalThis.pwned=true;/**']];
        $schemas['Named'] = ['type' => 'object', 'properties' => [
            'bad*/name' => ['type' => 'string'],
        ]];
        $symbols['Status'] = 'Status';
        $symbols['Named'] = 'Named';
        $expanded = new SdkModel($model->apiVersion, $schemas, $symbols,
            $model->operations, $model->webhooks, $model->fingerprint);

        $types = (new JavaScriptEmitter())->emit($expanded)['types.js'];
        self::assertStringNotContainsString('*/globalThis.pwned', $types);
        self::assertStringNotContainsString('bad*/name', $types);
        self::assertStringContainsString('*\\u002FglobalThis.pwned', $types);
        self::assertStringContainsString('bad*\\u002Fname', $types);
    }

    private static function model(): SdkModel
    {
        $user = ['type' => 'object', 'properties' => [
            'id' => ['type' => 'integer', 'readOnly' => true],
            'nickname' => ['type' => ['string', 'null']],
            'secret' => ['type' => 'string', 'writeOnly' => true],
        ], 'required' => ['id', 'secret']];
        $pageMeta = ['type' => 'object', 'properties' => ['page' => ['type' => 'integer']],
            'required' => ['page']];
        $page = ['type' => 'object', 'properties' => [
            'data' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/User']],
            'meta' => ['$ref' => '#/components/schemas/SqueHubPaginationMeta'],
        ], 'required' => ['data', 'meta']];
        $common = [
            'method' => 'GET', 'api_version' => 'v2', 'request_body' => null,
            'security' => ['type' => 'pat'],
        ];
        $show = $common + [
            'operation_id' => 'users.show', 'symbol' => 'UsersShow',
            'segments' => ['users', 'show'], 'path' => '/api/v2/users/{id}',
            'parameters' => [['name' => 'id', 'in' => 'path', 'required' => true,
                'schema' => ['type' => 'integer']]],
            'responses' => [
                '200' => ['schema' => ['$ref' => '#/components/schemas/User'],
                    'content_type' => 'application/json'],
                '204' => ['schema' => null, 'content_type' => null],
            ],
        ];
        $list = $common + [
            'operation_id' => 'users.list', 'symbol' => 'UsersList',
            'segments' => ['users', 'list'], 'path' => '/api/v2/users',
            'parameters' => [],
            'responses' => ['200' => ['schema' => $page, 'content_type' => 'application/json']],
        ];
        return new SdkModel('v2', ['SqueHubPaginationMeta' => $pageMeta, 'User' => $user],
            ['SqueHubPaginationMeta' => 'SqueHubPaginationMeta', 'User' => 'User'],
            [$show, $list], [], str_repeat('0', 64));
    }
}
