<?php

declare(strict_types=1);

namespace SqueHub\Tests\Unit;

use App\Api\Sdk\SdkException;
use App\Api\Sdk\SdkOutput;
use PHPUnit\Framework\TestCase;
use SqueHub\Tests\Fixtures\TemporaryProject;

require_once dirname(__DIR__) . '/Fixtures/TemporaryProject.php';

/** Covers generated-file ownership without touching the application checkout. */
final class SdkOutputTest extends TestCase
{
    private TemporaryProject $project;

    protected function setUp(): void
    {
        $this->project = new TemporaryProject();
    }

    protected function tearDown(): void
    {
        $this->project->remove();
    }

    public function testRegenerationPreservesUserFilesAndRemovesOnlyOwnedStaleFiles(): void
    {
        $output = new SdkOutput($this->project->path());
        $first = $this->files(['client.ts' => $this->source('first'),
            'old.ts' => $this->source('old')]);
        self::assertTrue($output->sync('Generated/Client', $first, 'typescript', false));
        $this->project->write('Generated/Client/notes.txt', 'user-owned');
        self::assertTrue($output->sync('Generated/Client', $first, 'typescript', true));

        $second = $this->files(['client.ts' => $this->source('second')]);
        self::assertFalse($output->sync('Generated/Client', $second, 'typescript', true));
        self::assertSame($this->source('first'),
            file_get_contents($this->project->path('Generated/Client/client.ts')));
        self::assertTrue($output->sync('Generated/Client', $second, 'typescript', false));
        self::assertFileDoesNotExist($this->project->path('Generated/Client/old.ts'));
        self::assertSame('user-owned',
            file_get_contents($this->project->path('Generated/Client/notes.txt')));
        self::assertTrue($output->sync('Generated/Client', $second, 'typescript', true));
    }

    public function testPathTraversalAndProtectedRootsAreRejected(): void
    {
        $output = new SdkOutput($this->project->path());
        $files = $this->files(['client.ts' => $this->source('safe')]);
        foreach (['../Project', 'Generated/../App', 'App/Sdk', 'Project/Sdk',
            'vendor/Sdk', '.git/Sdk', '/absolute/path', 'C:\\absolute\\path'] as $path) {
            try {
                $output->sync($path, $files, 'typescript', false);
                self::fail('Unsafe SDK path was accepted.');
            } catch (SdkException) {
                self::assertTrue(true);
            }
        }
    }

    public function testUnownedTargetCannotBeOverwritten(): void
    {
        $output = new SdkOutput($this->project->path());
        $this->project->write('Generated/Client/client.ts', 'user source');
        $files = $this->files(['client.ts' => $this->source('generated')]);
        $this->expectException(SdkException::class);
        try {
            $output->sync('Generated/Client', $files, 'typescript', false);
        } finally {
            self::assertSame('user source',
                file_get_contents($this->project->path('Generated/Client/client.ts')));
        }
    }

    private function source(string $value): string
    {
        return "// Generated by SqueHub. Do not edit directly.\nexport const value = '" . $value . "';\n";
    }

    /** @param array<string,string> $sources @return array<string,string> */
    private function files(array $sources): array
    {
        $sources['squehub-sdk.json'] = json_encode([
            'squehub_sdk' => '1', 'language' => 'typescript',
            'files' => array_keys($sources),
        ], JSON_THROW_ON_ERROR) . "\n";
        return $sources;
    }
}
